### Login
# @name login
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "test2",
    "password": "123456"
}

### Set auth token from login response
@auth_token = {{login.response.body.token}}

### Register
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "username": "test2",
    "email": "test2@gmail.com",
    "password": "123456"
}

### Get All Posts
GET http://localhost:8000/posts
Authorization: Bearer {{auth_token}}

### Get My Posts
GET http://localhost:8000/me/posts
Authorization: Bearer {{auth_token}}

### Create Post
POST http://localhost:8000/posts
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "title":"This is a new post 2"
}

### Edit Post
PUT http://localhost:8000/posts/dbc6de99-dee7-4f54-8f8b-d0806505c5ef
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "title": "Updated Post Title"
}

### Delete Post
DELETE http://localhost:8000/posts/84ae1587-668d-4cad-b605-59064b6acac3
Authorization: Bearer {{auth_token}}